### PR TITLE
Emitter -> Host

### PR DESCRIPTION
**Pull request by mindplay-dk**
Okay, this is the big one, as proposed in the [comment](https://github.com/narrowspark/http-emitter/issues/13#issuecomment-467428285) in #13.

This reduces the whole thing to a single class that encapsulates the entire SAPI dispatch-cycle: bootstrapping the request from superglobals, dispatching a handler, and emitting the response.

If you agree with this approach, documentation will need an overhaul, and lots of things need to be mentioned in the change log.

As said, if you think this change is too drastic, I won't take offence at all :-)

Part of me wonders if this would make more sense as a new package in any case? It isn't strictly an emitter anymore, it's now a self-contained SAPI environment host for a request handler - and there isn't a single thing that's backwards compatible, other than the functionality of course.

~~(I hate to put pressure on you, but I have a deadline, so I need your response within a day or two - otherwise I have to proceed with a fork, since I have other things depending on this.)~~

### CODE REVIEW

**Comment by mindplay-dk** [comment]
Hey, my priorities just changed here, so no pressure - take your time :-)

Build configuration looks broken - I couldn't figure out what's picking up the `INSTALL_SWOOLE` flags in the Travis script? So I left it there for now.

Not sure what that has to do with my PR though - it doesn't depend on Swoole anymore, so...

**Comment by mindplay-dk** [comment]
@narrowspark any chance you can review this soon?

As said, it's cool if you're not interested - if so, I'll create a fork :-)

**Comment by prisis** [comment]
Hey :), sorry for the delay, im really sorry but this change is to much, it change the hole propose of this package. But thank you for your hard work and your pull requests!

**Comment by mindplay-dk** [comment]
No problem.

With the other changes merged, I could actually implement the Host concept as a package that depends on yours.

Only, I am not convinced that the concept of an Emitter is useful on its own, since it's only one part of a full request/response processing cycle - creating the Server Request is equally coupled to this cycle, and is different for e.g. FCGI and Swoole, so as far as I can figure, neither of these components are meaningful on their own.

But each to his own :-)

And you probably want to close #13 as well then, which is the basis for these changes.

Cheers :-)

**Comment by prisis** [comment]
Created a new version with all changes :) v0.8.0

**Pull request closed without merging**
