### PR TITLE
BREAKING CHANGE: upgraded package to support php v8 only

### PR DESCRIPTION
**Pull request by prisis**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | no

### CODE REVIEW

**Comment by someniatko** [comment]
@prisis Sorry in advance for disturbing. Just want to ensure you haven't forgot about this PR. Maybe there is some way for contributing if you don't have time?

**Comment by prisis** [comment]
Hey :), missing a bit o time, need to update a bit more packages and waiting for wikimedia/composer-merge-plugin to support composer 2

**Comment by bgoetschke** [comment]
Hi, nice to see PHP 8 support in the works as this is one of the packags that blocks PHP 8 support in applications i have to manage.

Is there any particular reason PHP 7 support is completely dropped when introducing PHP 8 support? To have a clear upgrade path in applications it would be nice to have at least an intermediate release that keeps the current PHP "^7.2" support together with PHP 8.

**Comment by prisis** [comment]
Hey :), in the end its my time, why im dropping the support for php7. V1 is stable without any changes, V2 will support php8 with only small improvements. Composer is handling versioning pretty good, so you can allow "^1.0 || ^2.0", for supporting php7 and php8

**Pull request merged**
